### ISSUE TITLE
Build Error on Android

### ISSUE THREAD

**Issue by cbcye** [yamill/react-native-orientation#114]
Environment: RN 0.35 & Android 5
Log:
MainApplication.java:47: error: constructor OrientationPackage in class OrientationPackage cannot be applied to given types;
                    new OrientationPackage(),
                    ^
  required: Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

**Comment by nidorx** [comment]
@cbcye, the version on https://www.npmjs.com/package/react-native-orientation is wrong.

For now, change version on you ```package.json``` from ```"react-native-orientation": "^1.17.0"```  to ```"react-native-orientation": "yamill/react-native-orientation"```

@yamill, please, publish a new version on npm.

**Comment by leechance** [comment]
Environment: RN 0.36 & Android 5


i meet the same error when complie android app @cbcye 
did you solved the problem ??
@nidorx  can you give me some idea 
@yamill, please, publish a new version on npm.

**Comment by Venryx** [comment]
@yamill I'm getting the same issue as the two above.

Fixed it with @nidorx's solution, but would be nice to have the npm module updated, so the build instructions work out-of-the-box.

**Comment by KBepo** [comment]
@nidorx getting same error but couldn't fix it by changing that in package.json

**Comment by asela-wijesinghe** [comment]
Same Here not fixed

**Comment by steveliles** [comment]
@KBepo and @asela-wijesinghe and anyone else still seeing the problem after applying @nidorx's solution: did you unlink the old version and re-link the new version? 

The signature of the `OrientationPackage` constructor changed, but you have to re-link in order to update `MainApplication` correctly.

**Comment by cmedinasoriano** [comment]
For anyone still having this problem after trying everything said here, try also replacing in the MainApplication.java
```java
new OrientationPackage(this),
```
with this
```java
new OrientationPackage(),
```

IMPORTANT, verify that `new OrientationPackage(),` is not repeated as it was in mine.

**Comment by RaguRam1991** [comment]
> For anyone still having this problem after trying everything said here, try also replacing in the MainApplication.java
> 
> ```java
> new OrientationPackage(this),
> ```
> 
> with this
> 
> ```java
> new OrientationPackage(),
> ```
> 
> IMPORTANT, verify that `new OrientationPackage(),` is not repeated as it was in mine.

this works for me afetr all, thanks!
